<?php

namespace Nextnetmedia\Tipalti\Resource;

class WSErrors
{
    public const __default = 'UnknownError';
    public const UnknownError = 'UnknownError';
    public const OK = 'OK';
    public const UnknownCountryCode = 'UnknownCountryCode';
    public const CountryNotSupported = 'CountryNotSupported';
    public const UnknownState = 'UnknownState';
    public const PayerUnknown = 'PayerUnknown';
    public const PayeeUnknown = 'PayeeUnknown';
    public const EncryptionKeyFailedValidation = 'EncryptionKeyFailedValidation';
    public const ParameterError = 'ParameterError';
    public const FeeScheduleUnknown = 'FeeScheduleUnknown';
    public const StringContainsNonEBCDICCharacters = 'StringContainsNonEBCDICCharacters';
    public const PreferredEntityIsNotValid = 'PreferredEntityIsNotValid';
    public const InvoiceRefCodeUnknown = 'InvoiceRefCodeUnknown';
    public const InvoiceCannotBeCancelled = 'InvoiceCannotBeCancelled';
    public const UnknownCurrencyCode = 'UnknownCurrencyCode';
    public const InvalidJson = 'InvalidJson';
    public const InvoiceValidationError = 'InvoiceValidationError';
    public const ValidationError = 'ValidationError';
    public const ValidationWarning = 'ValidationWarning';
    public const BillsModuleMustBeEnabled = 'BillsModuleMustBeEnabled';
    public const FileNotFound = 'FileNotFound';
    public const InvoiceFileNotFound = 'InvoiceFileNotFound';
    public const CannotReadFile = 'CannotReadFile';
    public const CannotDeleteFile = 'CannotDeleteFile';
    public const CannotWriteFile = 'CannotWriteFile';
    public const PaymentAmountTotalMismatch = 'PaymentAmountTotalMismatch';
    public const InvalidPayerIpAddress = 'InvalidPayerIpAddress';
    public const EnahncedSecurityNotConfigured = 'EnahncedSecurityNotConfigured';
    public const SubPayerIsNotFound = 'SubPayerIsNotFound';
    public const SubPayerDoensNotSupportDynamicKey = 'SubPayerDoensNotSupportDynamicKey';
    public const PayerDoesntSupportInvoiceModule = 'PayerDoesntSupportInvoiceModule';
    public const CustomFieldDoesNotExist = 'CustomFieldDoesNotExist';
    public const DuplicateInvoiceRefCode = 'DuplicateInvoiceRefCode';
    public const PaidOrInProcessInvoiceCannotBeUpdated = 'PaidOrInProcessInvoiceCannotBeUpdated';
    public const CanApproveNotSupported = 'CanApproveNotSupported';
    public const AuthorizationError = 'AuthorizationError';
    public const InvoiceNotApprovedbyPayee = 'InvoiceNotApprovedbyPayee';
    public const PaymentAmountCannotBeNegative = 'PaymentAmountCannotBeNegative';
    public const RequestLimitReached = 'RequestLimitReached';
    public const ItemAlreadyInProcess = 'ItemAlreadyInProcess';
    public const RequestDoesNotExist = 'RequestDoesNotExist';
    public const RequestStillInProgress = 'RequestStillInProgress';
    public const CustomFieldValueIsNotUnique = 'CustomFieldValueIsNotUnique';
    public const BillStatusIsNotSupported = 'BillStatusIsNotSupported';
    public const GLAccountAssignedToActiveBill = 'GLAccountAssignedToActiveBill';
    public const CustomFieldValidationError = 'CustomFieldValidationError';
    public const CustomFieldValueValidationError = 'CustomFieldValueValidationError';
    public const GlAccountValidationError = 'GlAccountValidationError';
    public const APAccountNotFound = 'APAccountNotFound';
    public const SyncDirectionInvalid = 'SyncDirectionInvalid';
    public const ErrorTypeInvalid = 'ErrorTypeInvalid';
    public const IntegrationNameInvalid = 'IntegrationNameInvalid';
    public const IntegrationVersionOverMaxLength = 'IntegrationVersionOverMaxLength';
    public const CreationTimestampInvalid = 'CreationTimestampInvalid';
    public const ErrorDetailsInvalid = 'ErrorDetailsInvalid';
    public const PaymentTermNotFound = 'PaymentTermNotFound';
    public const CustomFieldInvalidDateFormat = 'CustomFieldInvalidDateFormat';
    public const PaymentTermValidationError = 'PaymentTermValidationError';
    public const TaxCodeValidationError = 'TaxCodeValidationError';
    public const TaxCodeExternalIdNotFoundError = 'TaxCodeExternalIdNotFoundError';
    public const IllegalErpCurrencyUpdate = 'IllegalErpCurrencyUpdate';
    public const PurchaseOrderNotFound = 'PurchaseOrderNotFound';
    public const GoodsReceivedNotificationNotFound = 'GoodsReceivedNotificationNotFound';
    public const PayeeAlreadyInvited = 'PayeeAlreadyInvited';
    public const MissingEmail = 'MissingEmail';
    public const PayeeAlreadyRegistered = 'PayeeAlreadyRegistered';
    public const PayeeEmailNotUnique = 'PayeeEmailNotUnique';
    public const SupplierPortalDisabled = 'SupplierPortalDisabled';
    public const ReportNotFound = 'ReportNotFound';
}
